### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by noelb** [Mathigon/fermat.js#1]
Great library! 

One small thing I noticed, "manhatten" distance is spelled wrong, should be "manhattan".
https://github.com/Mathigon/fermat.js/blob/master/src/geometry.js

**Comment by plegner** [comment]
Thanks for spotting this!

Fixed in https://github.com/Mathigon/fermat.js/commit/70bf6515870cb265dcee03987bcf653f8fb5e05b
