### ISSUE TITLE
intersections() appears hanging forever when calculating intersection of polygon and line

### ISSUE THREAD

**Issue by manuel-koch** [mathigon/fermat.js#15]
I have a polygon that has approximated shape of ellipsis and a line that has one point inside that ellipsis.
Trying to find intersection of polygon and line.
Somehow the `intersections()` call never returns or hangs.

I'm using the same procedure to calculate intersection of other ( likely less points ) polygon and a line successfully.
Could it be that implementation can't handle polygons with too many points ?
API documentation doesn't state any known limitation though.

Using @mathigon/fermat 0.5.2.
Code fails when running in Chrome "Version 84.0.4147.125 (Offizieller Build) (64-Bit)".

```
const polygonPoints = [
  new Point(-349, 219),
  new Point(-350.2913409939623, 227.6824088833465),
  new Point(-354.1261272331978, 236.10100716628344),
  new Point(-360.38784067832273, 244),
  new Point(-368.88622233488684, 251.13938048432698),
  new Point(-379.36305317664414, 257.3022221559489),
  new Point(-391.5, 262.30127018922195),
  new Point(-404.92828781731816, 265.98463103929544),
  new Point(-419.2399048983109, 268.2403876506104),
  new Point(-434, 269),
  new Point(-448.7600951016891, 268.2403876506104),
  new Point(-463.07171218268184, 265.98463103929544),
  new Point(-476.5, 262.30127018922195),
  new Point(-488.63694682335586, 257.3022221559489),
  new Point(-499.1137776651131, 251.13938048432698),
  new Point(-507.61215932167727, 244),
  new Point(-513.8738727668022, 236.10100716628344),
  new Point(-517.7086590060377, 227.68240888334654),
  new Point(-519, 219),
  new Point(-517.7086590060377, 210.3175911166535),
  new Point(-513.8738727668023, 201.89899283371656),
  new Point(-507.61215932167727, 194),
  new Point(-499.11377766511316, 186.86061951567302),
  new Point(-488.63694682335586, 180.6977778440511),
  new Point(-476.50000000000006, 175.69872981077808),
  new Point(-463.0717121826819, 172.0153689607046),
  new Point(-448.7600951016891, 169.7596123493896),
  new Point(-434, 169),
  new Point(-419.23990489831095, 169.75961234938958),
  new Point(-404.9282878173182, 172.01536896070456),
  new Point(-391.5, 175.69872981077808),
  new Point(-379.36305317664414, 180.6977778440511),
  new Point(-368.8862223348869, 186.86061951567302),
  new Point(-360.38784067832273, 193.99999999999997),
  new Point(-354.1261272331978, 201.89899283371653),
];
const line = new Line(new Point(-434, 219), new Point(-229.5, 385.123));
console.info('polygon', polygonPoints.length);
const shape = new Polygon(...polygonPoints);

// the following call never seems to return
let intersection = intersections(line, shape) || [];
console.info('intersections', intersection.length);
```

**Comment by manuel-koch** [comment]
When using less points ( e.g. stripping last points, using total of just 21 polygon points ) seems to result in expected intersection - though it takes ~1.3sec to get result.

**Comment by plegner** [comment]
It seems like our current implementation simply converts polygons into an array of edge segments when finding intersections, but then also tries to find pairwise intersections for all of these (which grows very quickly for large polygons). I'm working on a fix now!

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/fermat.js/commit/50280f7b01d7db501143d7c279c6e6203f2d24a6 and NPM version `0.5.3`. I've also added a test that intersecting two 100-sided polygons takes <1s.

**Comment by manuel-koch** [comment]
Thanks for this really quick fix 👍  - I don't see the problem anymore !
